### ISSUE TITLE
`fable_modules` import issue

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable.Python#30]
Suppose I select an output directory for `fable-py`, say `mypackage`, then fable generates such file tree:

```
src/
   A.fs
   B.fs

mypackage/
    fable_modules/
        fable_library/
            map.py
            reflection.py
            ...
    A.py
    B.py
``` 

However, the generated code does not run, because both A.py and B.py reference `fable_modules` via absolute import:

```python
from fable_modules.fable_library.array import (map as map_1, iterate, initialize, fill)
```

Then `fable_modules` are not resolved as it is not in the top-level.

## current workaround

We can simply add the search path in `mypackage.__init__.py`:

```python
import sys
import os
sys.path.append(os.path.dirname(__file__))
```

However, this suffers from search path pollution, disabling importing more than one fable-generated python packages into the runtime.

## possible solution 

We could avoid generating `fable_modules` per package, and use something like  `https://pypi.org/project/fable-library/` for all fable-generated python package.

**Comment by dbrattli** [comment]
Python imports can be tricky so I need some more details. What do you mean by run? Which file here is the program? Is this a program or a library, and if it's a program then which file is the program. What does you fsproj look like?

**Comment by thautwarm** [comment]
> What do you mean by run?

I'm going to import the generated code as python package, and I set `--outDir` to a separate directory.

> What does you .fsproj look like?

For instance, I'm now trying to export OCaml sedlex to Python, and the `.fsproj` is quite simple:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <NoWarn>3370</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Sedlex.fs" />
    <PackageReference Include="Fable.Core.Experimental" Version="4.0.0-alpha-020" />
  </ItemGroup>

</Project>
```

**Comment by dbrattli** [comment]
Thanks, for a library (like this) the imports should not have been absolute so need to fix. I should be able to take a closer look at this later today.

**Comment by dbrattli** [comment]
Note that for Fable Python we have several different types of use-cases for imports that makes things a bit tricky:

1. file referencing another file in the same project
2. file referencing another file outside the same project (fsproj can reference any file wherever)
3. file referencing something in fable library
4. file referencing another file in a project reference
5. file referencing a fable NuGet with source included (will be added to fable-modules)

In addition, the compiled project may be a "Library" or "Exe". For libraries we need to use relative imports since we don't know the base library from where it will be used. For programs we must use absolute imports.

Anyways, adding fable-library to PyPI will only solve parts of the problem. We cannot do the same with e.g project and NuGet references. These are currently compiled together with the main project (as one big project). Having any project reference, NuGet, fable-library as locally installed packages is a possibility but it's not trivial to convert these to valid Python packages that can be pip-installed. I'm not saying it can't be done, just that it's not trivial. That'a why everything is currently compiled together as one big package for now. I btw think I have a fix ready for this import issue, so stay tuned. Just need to make sure I don't break anything else ...

**Comment by thautwarm** [comment]
This is a hard problem. Very sorry that I have to work for my tasks(big thanks to you and fable-python!) for a while. So far I  managed to get things work though I noticed a bunch of bugs...
Will try to give a hand since one or two months later!

**Comment by dbrattli** [comment]
Please try https://www.nuget.org/packages/fable-py/4.0.0-alpha-021 and see if it fixes the problem for now

**Comment by thautwarm** [comment]
I can confirm it works for the directory structure given above. I can now put my F\# source files into the `src` directory, which feels good to me.

However, when putting `.fsproj` into the `src` directory, `fable_modules` is still absolute imported and generated inside the output directory. This is still an issue, but things work all well if we put `.fsproj` into root directory.

**Comment by dbrattli** [comment]
https://github.com/fable-compiler/Fable/pull/2692

**Comment by dbrattli** [comment]
This issue should now hopefully be fixed in -alpha-22

**Comment by thautwarm** [comment]
Sorry that I don't have bandwidth to test it before a deadline on Jan 7th. Will do this later once my schedule gets released.

**Comment by dbrattli** [comment]
Should be fixed. Please re-open if you still have issues
