### ISSUE TITLE
[Transpilation] mapping anonymous records to python dictionaries breaks IComparable

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable.Python#35]
```fsharp
type S = S of {| x: int |}

let map = Map.ofList [S {| x = 1|} , 1]
```

running such code got us an exception:

```python
...\fable_modules\fable_library\types.py", line 90, in __lt__
    return self.fields < other.fields
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

The exception happens in `Union.__lt__`, where we directly compare dictionaries and fail...

As anonymous records are immutable, we might consider some immutable and structural data types. [pyrsistent](https://github.com/tobgu/pyrsistent/) might be helpful here.

**Comment by dbrattli** [comment]
Should be fixed in alpha-22. Currently using dictionaries in Python to match with Fable (js) is using objects. The suggestion of using an immutable type is good and we may consider changing is this at some later point in time. Perhaps just using the F# map impl. But I'll discuss this with the other Fable maintainers.
